### ISSUE TITLE
reference eronnée de dossier

### ISSUE THREAD

**Issue by MarlyseCLEMENT** [MTES-MCT/parcours_r_socle_introduction#17]
Dans le 3.3 du support en ligne 
"Copier/coller dans ce dossier le sous-dossier “data” fourni par les formateurs"
or on y accède avec savoirfR et le dossier est "extdata"

l'installation de savoirfR etant indispensable et le paragraphe sur ce point étant après peut etre mettre un lien vers savoirfR ?

dans le 5.8  Le fichier source (Excel) figure dans le sous-répertoire “data” et contient toutes les métadonnées.
une fois que le fichier de métadonnées sera dans savoir faire, changer le nom du repertoire ...?

**Comment by jengelaere** [comment]
c'était en effet bancal, c'est corrigé !
