### ISSUE TITLE
Detail pour savoirfR

### ISSUE THREAD

**Issue by MarlyseCLEMENT** [MTES-MCT/parcours_r_socle_introduction#18]
Bonjour à tous,

Je ne sais pas si c'est possible et adapté mais dans le chapitre 4 sur la partie savoirfR

je n'ai pas vu precisé (ou je ne m'en souviens pas) en amont qu'il faut installer remotes, et potentiellement l'appeler avec library 
remotes::install_github("MTES-MCT/savoirfR")

Le developpement du teletravail (et meme sans j'ai été confronter au probleme) serait il possible et envisageable, sans faire peur a tout le monde, de prevoir un paragraphe sur le .Renviron (et le proxy qu'il faut y attacher ?)
ainsi que eventuellement le super package qui permet de le desactiver / activer facilement (ainsi que redemarrer Rstudio qui est indispensable pour la prise en compte ?)

Merci d'avance !

**Comment by jengelaere** [comment]
J'ai ajouté install.packages("remotes") en effet, c'est pas évident au début.
Pour le proxy et le Renviron on cite https://github.com/MTES-MCT/parcours-r/wiki/Installation-de-R-et-RStudio-Desktop-au-MTE qui aide à configurer son R et son .Renviron.
Pour le super package qui permet de le desactiver / activer, je suis pas au clair la dessus, mais ce sera dans ce même wiki qu'on en parlera.

**Comment by jdlom** [comment]
J'ai ajouté la partie sur `configproxyr`
