### ISSUE TITLE
chapitre 8, soucis de comprehension

### ISSUE THREAD

**Issue by MarlyseCLEMENT** [MTES-MCT/parcours_r_socle_introduction#21]
Bonjour à tous,

[je me lache mais tant que je le vois]

Dans le corigé comme dans l'excercie
Excercice : "Faire un barplot du nombre de communes par type ZAU"

Corrige : "Faites maintenant un barplot (qui n’est pas un histogramme !!!!) du nombre de communes par type ZAU.

ggplot(data = base, aes(x = REG)) +
  geom_bar()"

Commentaire : 
Sauf que le barplot ainsi fait represente le nombre de commune par région non ? pas par type de ZAU ?
par ZAU il est faisable mais illlisble 
ggplot(data = base, aes(x = ZAU)) +
  geom_bar()
![Barplot ZAU](https://user-images.githubusercontent.com/96878048/147770092-6091e258-7cdf-4b98-885b-df0123628191.png)

**Comment by jengelaere** [comment]
Bien vu 👍  !
