### ISSUE TITLE
FUNFACT : fonction fill de l'excercie 8.6 point 4 de l'excercice

### ISSUE THREAD

**Issue by MarlyseCLEMENT** [MTES-MCT/parcours_r_socle_introduction#22]
Bonjour,

Bon la pour le fun moi j'ai fait Fill avec ZAU du coup 
ggplot(data = base, aes(x = REG, fill = ZAU)) +
  geom_bar()

Voici le graphique ^^
Pas très lisible a cause de la legende, mais ca donne une info complementaire...
![BarPlot REG - ZAU](https://user-images.githubusercontent.com/96878048/147770372-d5f72914-9c62-4a20-ac13-7a728a265e57.png)

**Comment by jengelaere** [comment]
oui, c'est très joli ! 😍 
comme c'est vu plutôt lors du m5, on n'intègrera pas au M1 qui est une découverte de R, il ne faut pas surcharger les stagiaires.
