### ISSUE TITLE
Corrige de l'excercice du chapitre 8

### ISSUE THREAD

**Issue by MarlyseCLEMENT** [MTES-MCT/parcours_r_socle_introduction#23]
Bonjour,
Dans le corrigé je vois aussi ce code  et le graphique associé
ggplot(data = base, aes(x = log(P14_POP), y = log(P14_LOGVAC))) +
  geom_point()

Sauf erreur de ma part il n'y a pas de point correspondant dans l'excercice...

    Réaliser un histogramme de la population communale
    Transformer les données avec la fonction log pour y voir plus clair
    Faire un barplot du nombre de communes par type ZAU
    Utiliser le paramètre fill de la fonction aes() pour améliorer le graphique
    Réaliser un graphique (nuage de points) croisant la densité de population et le taux de mortalité
    Ajouter une dimension supplémentaire avec la couleur des points (paramètre color de aes())

**Comment by jengelaere** [comment]
C'est les limites de l'exercice quand on fait la formation en solitaire, lors de la correction, on montre comment aller plus loin, mais ce n'est pas dans les objectifs du module 1 que de faire du ggplot de manière avancée
