### ISSUE TITLE
Chapitre 9 RData

### ISSUE THREAD

**Issue by MarlyseCLEMENT** [MTES-MCT/parcours_r_socle_introduction#24]
Dans le code 
save(base, V1, file = "outputs/petit_env.RData") # sauvegarde des éléments base et V1
Je n'ai pas de fichier V1 , je l'ai loupé ?

Il y a aussi une coquille (le guillemet d'entrée est mal placé)
load(outputs/"petit_env.RData") 
mais 
load(**"**outputs**/p**etit_env.RData")

**Comment by MarlyseCLEMENT** [comment]
correction proposée

**Comment by jengelaere** [comment]
👍 
V1 était créé au chap 5 `V1 <- c(1, 14, NA, 32.7)` mais effacé au chap 8, au niveau des histogrammes.
J'ai remplacé par un obj qui existe toujours !
