### ISSUE TITLE
Plan chapitre 10

### ISSUE THREAD

**Issue by MarlyseCLEMENT** [MTES-MCT/parcours_r_socle_introduction#26]
Bonjour à tous,

J'ai ^peut etre tord mais pour moi  "Pour aller plus loin : matrices et arrays"  , ne fait pas partie des "boucle " du 10.4

Ne serait il pas mieux de faire ?
10.5 Pour aller plus loin 
[avec]
10.5.1 Matrice et array
10.5.2 Inspection d’un objet : la régression

**Comment by jengelaere** [comment]
oui, tout à fait 🙏
