### ISSUE TITLE
Construction d'image docker pour améliorer le déploiement et l'intégration continue

### ISSUE THREAD

**Issue by jdlom** [MTES-MCT/parcours_r_socle_introduction#9]
L'idée est de construire des images docker (pour figer les environnements) car j'ai remarqué que quelques CI échouaient notamment à cause de dépendances non résolues (sf, rgeos.. pour ne citer que ceux-ci).

## Proposition

Créer une image docker basée sur `rocker/geospatial`  ou directement celle construire par l'inseefrlab `inseefrlab/rstudio` qui dépend d'ailleurs de `rocker/geospatial`

## Explications
L'image dépendra de `renv` et sera construite par une `gha` automatiquement notamment quand le `renv.lock` est modifié.
La `gha` de déploiement de chaque module de formation se basera sur cette image pour lancer le build du site dans ce `container`.
Il y aura donc autant d'images docker que de dépôt. Ces images varieront très peu (en fonction des packages utlisées)

## Bénéfices

- Possibilité d'utiliser le sspcloud pour contribuer
- En utilisant ce système, on s'assure que le code produit par un contributeur tournera à priori même sur un developpement local
- Moins de failed de ci donc moins de noeuds au cerveau

## Faiblesses

- J'en vois pas mais peut-être qu'il y en a

**Comment by MaelTheuliere** [comment]
Oui c'est une bonne idée ! Il faudra ensuite documenter tout cela, car déjà gha est peu maitrisé au sein du groupe, ce sera encore une montée en compétence à accompagner.

**Comment by jengelaere** [comment]
On discutait avec Murielle ce matin de l'utilité de renv dans nos support, si on s'en passait, ça fout tout en l'air ?

**Comment by jdlom** [comment]
Renv, c'est bien dans la pratique mais c'est un peu lourd quand tu mets à jour. Si on utilise seulement docker ça doit pouvoir suffir pour faciliter le CI et le déploiement dans le sspcloud. 
Je trouve globalement que les installations fonctionnent souvent mieux avec les dernières versions de paquet

**Comment by MaelTheuliere** [comment]
L'avantage de renv, c'est que quand tu as une mise à jour majeur d'un package utilisé avec breaking change, ça ne casse pas tout..

**Comment by jdlom** [comment]
Je propose de clôturer cette issue. On en ouvrira une si on rediscute de l'intérêt de renv avec docker.

**Comment by jengelaere** [comment]
D'autant qu'aujourd'hui, on a des packages nécessaires qui ne s'installent que grâce à renv pour la compilation des supports. Mais il faudrait enrichir le wiki avec un tuto renv pour ne pas décourager les référents qui ne connaissent pas.
